import type { Metadata } from "next";
// Metadata 페이지의 헤더 내용에 포함시킬 메타데이터
import { Inter } from "next/font/google";
// 폰트 가져온것. Inter
import "./globals.css";

// 폰트 적용
// Inter 폰트를 생성하면서 문자 집합 정해준거
const inter = Inter({ subsets: ["latin"] });

// 메타데이터 지정
export const metadata: Metadata = {
  title: "Create Next App", // 페이지의 제목
  description: "Generated by create next app", // 페이지의 설명
};

// 처으메 전역으로 사용할 레이아웃
// 이 레이아웃은 제거하면 안된다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // react node 타입
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        여기는 루트 레이아웃
        {children}
      </body>
    </html>
  );
}
